### PR TITLE
Code improvement branch

### PR DESCRIPTION
**Pull request by vishal804**
Hello

### CODE REVIEW

**Review by parulgupta2001 — APPROVED** [review]
Everything looks good. You can merge.

**Review by vermasavita — COMMENTED** [review]
When I am clicking on create new post button it redirects mei to feedpage
- While clicking on Guest Login, first auto fill the credential and then login. It's good in terms of UX

**Comment by vishal804** [comment]
> When I am clicking on create new post button it redirects mei to feedpage
> 
> * While clicking on Guest Login, first auto fill the credential and then login. It's good in terms of UX

Will try to do

**Comment by shivamSspirit** [comment]
lgtm

**Pull request merged**
